name: Send Discord Message

on:
  schedule:
    - cron: "*/10 * * * *"  # testing
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # needed to push state.json

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SCHEMA: ${{ secrets.SCHEDULE }}
        run: python discord_poster.py

      - name: Commit state
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add state.json
          git commit -m "Update cleaning state" || echo "No changes"
          git push
